In [2]:
import tensorflow as tf

In [3]:
text_ds = tf.data.TextLineDataset("/Users/saksh.menon/Documents/GitHub/C-RNN-approach/manual_dataset/FILTERED_DATASET.txt").filter(lambda x: tf.cast(tf.strings.length(x), bool))

2024-02-23 02:13:36.892064: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-02-23 02:13:36.892086: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-02-23 02:13:36.892094: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-02-23 02:13:36.892166: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-23 02:13:36.892187: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
codelines = []
with open('FILTERED_DATASET.txt') as obj:
    codelines = obj.readlines()

codelines

['#include <stdio.h>\n',
 '\n',
 'int main(void)\n',
 '{\n',
 '    int result = 1;\n',
 '    if (result == 1)\n',
 '    {\n',
 '        printf("Executing critical code...\\n");\n',
 '    }\n',
 '    else\n',
 '    {\n',
 '        printf("Exiting out...\\n");\n',
 '        return 1;\n',
 '    }\n',
 '\n',
 '    return 0;\n',
 '}\n']

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
vectorizer = TfidfVectorizer()
output = vectorizer.fit_transform(codelines)
output

<17x15 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [15]:
inverse_vocab = {index: token for token, index in vectorizer.vocabulary_.items()}
print(inverse_vocab[])
# vectorizer.get_vocabulary()

{6: 'include', 13: 'stdio', 7: 'int', 8: 'main', 14: 'void', 11: 'result', 5: 'if', 10: 'printf', 3: 'executing', 1: 'critical', 0: 'code', 2: 'else', 4: 'exiting', 9: 'out', 12: 'return'}


In [36]:
for i in enumerate(output):
    print(i[1].A[:1])
    print("\t=>\t ")
    print(codelines[i[0]])
    print()
    

[[0.         0.         0.         0.         0.         0.
  0.70710678 0.         0.         0.         0.         0.
  0.         0.70710678 0.        ]]
	=>	 
#include <stdio.h>


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
	=>	 



[[0.         0.         0.         0.         0.         0.
  0.         0.52536105 0.6016626  0.         0.         0.
  0.         0.         0.6016626 ]]
	=>	 
int main(void)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
	=>	 
{


[[0.         0.         0.         0.         0.         0.
  0.         0.70710678 0.         0.         0.         0.70710678
  0.         0.         0.        ]]
	=>	 
    int result = 1;


[[0.         0.         0.         0.         0.         0.75325488
  0.         0.         0.         0.         0.         0.65772873
  0.         0.         0.        ]]
	=>	 
    if (result == 1)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
	=>	 
    {


[[0.51554289 0.51554289 0.         0.51554289 0.         0.
 