In [1]:
import platform
import os
import numpy as np
import keras
from keras import layers

if platform.machine() == 'x86_64':
    os.chdir("/home/sakshmeno/Documents/GitHub/Faulthunter-RNN-approach")
elif platform.machine() == 'arm64':
    os.chdir("/Users/saksh.menon/Documents/GitHub/Faulthunter-RNN-approach")

from Utils.dataframe_gen import *
from Utils.OneHot_gen import *
from Utils.TFIDF_gen import *
from Utils.word2vec_gen import *
from Utils.vector_gen import *

#test


2024-03-04 15:39:28.439640: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-04 15:39:28.479384: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-04 15:39:28.479413: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-04 15:39:28.480884: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-04 15:39:28.487090: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-04 15:39:28.488277: I tensorflow/core/platform/cpu_feature_guard.cc:1

FileNotFoundError: [Errno 2] No such file or directory: '/home/sakshmeno/Documents/GitHub/C-RNN-approach/Labels/Labelling_Prateek_Guillermo.xlsx'

In [2]:
original_df = dataframe_init()
word2vec_df = original_df.copy()
word2vec_df = word2vec_init(word2vec_df)

NameError: name 'dataframe_init' is not defined

In [ ]:
vectors = vec_split(word2vec_df)
tensors = tensor_gen(vectors)

In [4]:
model = keras.Sequential()

model.add(layers.Input((218, 1)))
model.add(layers.SimpleRNN(256, return_sequences=True, dropout=0.4))
model.add(layers.SimpleRNN(256, return_sequences=True, dropout=0.4))
model.add(layers.SimpleRNN(256, dropout=0.4))
model.add(layers.Dense(256, activation=keras.activations.relu)) #kernel_regularizer=keras.regularizers.l2(0.01)
model.add(layers.Dense(256, activation=keras.activations.relu ))
model.add(layers.Dense(256, activation=keras.activations.relu ))
model.add(layers.Dense(2, activation = keras.activations.softmax))

model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.01), loss=keras.losses.BinaryFocalCrossentropy(apply_class_balancing=True,gamma=2),
              metrics=["accuracy"], )
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 218, 256)          66048     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 218, 256)          131328    
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 256)               131328    
                                                                 
 dense (Dense)               (None, 256)               65792     
                                                                 
 dense_1 (Dense)             (None, 256)               65792     
                                                                 
 dense_2 (Dense)             (None, 256)               65792     
                                                                 
 dense_3 (Dense)             (None, 2)                 5

In [5]:
history = model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10


2024-02-29 22:43:37.888076: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


  1/131 [..............................] - ETA: 2:16:11 - loss: 0.1514 - accuracy: 0.4688

KeyboardInterrupt: 

In [ ]:
y_pred = model.predict(x_test)

33/33 [==============================] - 3s 81ms/step


In [ ]:
list(y_pred)

[array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 0.08374306], dtype=float32),
 array([0.91625696, 

In [ ]:
(y_test[1040])

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>